import { Cormorant_Garamond, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

const cormorantGaramond = Cormorant_Garamond({
	variable: "--font-comorant-garamond",
	subsets: ["latin"],
	weight: "300",
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	weight: "400",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${cormorantGaramond.variable} ${inter.variable}`}>{children}</body>
		</html>
	);
}
